#
# Script
#
clear

./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/b1_ss.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cage3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/LFAT5_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/LFAT5_M.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2dal_bci_Aside.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Ragusa18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/LF10_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cage4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Ragusa16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/LF10_M.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/d_ss.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Hamrle1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/GD99_b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/football.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Sandi_authors.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/GD01_c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Trefethen_20b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/d_dyn1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2dal_bci_Abottom.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mesh1em6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mesh1e1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mesh1em1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/pores_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bfwb62.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2dal_bci_Atop.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/west0067.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/impcol_b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/impcol_c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/GD97_c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/west0156.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nos4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cage5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/west0132.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/gre_115.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/odepb400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/impcol_a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/GD01_a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bfwa62.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rw136.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/west0167.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/pivtol.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lns_131.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lnsp_131.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/gre_216a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/SmallW.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/steam3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nos1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/CAG_mat72.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mesh3e1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rotor1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rajat11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/GD00_c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Trefethen_150.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/S10PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/M10PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/odepa400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/S10PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/M10PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/gre_216b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/gre_185.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mesh3em5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/robot.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rdb200l.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/impcol_d.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Trefethen_200b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/gre_343.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/saylr1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/G11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/G13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/G12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/shl_0.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/GD96_a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/shl_400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/shl_200.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rajat05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/494_bus.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cage6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/impcol_e.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lop163.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/celegans_metabolic.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lund_a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mesh2e1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lund_b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mesh2em5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/pde225.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rajat14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_183_6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_183_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/plskz362.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_183_4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_183_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ck104.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/gre_512.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Trefethen_300.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/jazz.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/west0497.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nos6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mhdb416.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/662_bus.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bfwb398.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nnc261.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/tols90.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/west0479.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/arc130.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/USAir97.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/M20PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/S20PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rw496.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_56.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_54.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_57.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_51.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_50.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_52.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_53.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_55.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_48.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_49.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_47.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_46.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_45.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_dcop_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/S20PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/M20PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/west0381.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/str_0.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/olm500.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/oscil_trans_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/685_bus.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/sherman1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/saylr3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rdb450l.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nos7.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/tols340.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ww_36_pmec_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bp_0.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/netscience.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nos2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/str_200.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nos5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/qh768.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/str_400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cz148.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/west0655.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/str_600.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/G19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bp_200.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/G21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/G20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/G18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/G32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/G33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/G34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Trefethen_500.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/gr_30_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bp_400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mcca.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bp_600.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/qh882.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/young3c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/filter2D_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lns_511.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/west0989.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/steam1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lnsp_511.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bp_800.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_680_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/b2_ss.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/tols1090.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bp_1000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Journals.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bp_1200.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_680_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ck400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bp_1400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_680_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bp_1600.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bfwa398.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/dw256A.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/dwa512.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/jpwh_991.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/S40PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/M40PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/dw256B.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/dwb512.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/S40PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/M40PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/poisson2D.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rdb800l.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Chebyshev1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/sherman4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Trefethen_700.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/olm1000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bfwb782.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nnc666.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/pores_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/problem1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cdde4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cdde3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/tub1000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cdde6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cdde2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rdb968.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cdde1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cdde5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cage7.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/tols2000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/gre_1107.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/utm300.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Chem97ZtZ.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/b_dyn.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/laser.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/west1505.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/plat362.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cz308.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/orsirr_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rajat19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hor_131.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/qh1484.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/pde900.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_541_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_541_4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/poli.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ck656.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_541_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rdb1250l.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/iprob.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/orsirr_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_541_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/SciMet.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/S80PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/M80PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/west2021.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/S80PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/M80PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/circuit204.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/CAG_mat364.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2dal_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2dal_bci_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2dal_e.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bfwa782.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/plsk1919.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mahindas.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/tols4000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_760_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_760_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/olm2000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fs_760_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rail_1357_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_51.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_47.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_45.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_48.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_46.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_49.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_50.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rajat04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_dcop_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nos3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nnc1374.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mhda416.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cz628.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/zenios.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Pd.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/steam2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rotor2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rbsa480.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rbsb480.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rdb2048_noL.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bwm2000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/m3plates.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_trans_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fpga_trans_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/pores_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/plbuckle_G.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/polblogs.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lung1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rajat12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/epb0.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/watt_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/saylr4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/watt_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/orsreg_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Trefethen_2000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Si2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/dw1024.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/dw2048.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mhd3200b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cage8.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Alemdar.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/PGPgiantcompo.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rdb3200l.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/flowmeter0_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/flowmeter5_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/pde2961.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/init_adder1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/DK01R.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_46.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_49.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_50.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_57.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_56.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_51.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_53.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_61.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_65.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_58.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_69.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_62.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_63.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_52.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_59.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_48.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_60.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_47.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_68.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_66.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_45.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_67.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_64.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_55.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_dcop_54.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/radfr1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/extr1b_A_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/TSOPF_FS_b9_c1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cryg2500.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cz1268.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/msc01050.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/wang1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/wang2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/olm5000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/shyy41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/sherman3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/meg4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_trans_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/adder_trans_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/add20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/sherman5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/qpband.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/msc00726.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mhd4800b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/swang2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/swang1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/coater1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Sieber.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/sherman2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_47.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_75.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_64.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_53.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_71.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_60.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_50.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_63.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_56.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_70.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_59.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_74.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_46.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_55.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_49.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_62.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_69.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_67.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_58.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_52.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_66.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_73.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lhr01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/tuma2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/poli_large.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/eurqsa.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/g7jac010sc.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bloweybq.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cell2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Hamrle2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Lederberg.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rdb5000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mcfe.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/circuit_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/plat1919.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/shermanACa.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nopoly.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nasa1824.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/poli3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lns_3937.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lnsp3937.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ncvxqp9.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Chebyshev2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cell1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/sit100.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/msc01440.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/utm1700b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rail_5177_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/add32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/n3c6-b7.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2dal_a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Zewail.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t3dl_e.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_45.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_54.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_48.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_51.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_65.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_57.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_68.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_61.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_72.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ncvxqp1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/gemat12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fv3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/gemat11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_76.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/jan99jac020sc.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/hydr1c_A_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cz2548.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fv1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/fv2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lhr02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/tomography.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex10hs.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rajat03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/tuma1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstm39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rajat13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nasa2146.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bips98_606.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bcsstk13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/poli4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/pesa.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bips98_1142.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/viscoplastic1_C_6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/sts4098.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/g7jac020sc.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/dw4096.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/dw8192.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Chebyshev3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/shermanACd.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/c-44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cage9.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/viscoplastic1_C_7.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/nopss_11k.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bips98_1450.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/viscoplastic1_C_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/utm3060.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/circuit_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/big.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/viscoplastic1_C_4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/viscoplastic1_C_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/xingo_afonso_itaipu.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mimo46x46_system.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/viscoplastic1_C_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ww_vref_6405.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mimo28x28_system.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/zeros_nopss_13k.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mimo8x8_system.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bips07_1693.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/msc04515.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/viscoplastic1_C_5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mark3jac020sc.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/Kaufhold.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex7.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/TSOPF_RS_b9_c6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex9.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cryg10000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cz5108.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/LFAT5000_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rdist2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/jan99jac040sc.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/linverse.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rdist3a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/LFAT5000_M.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/garon1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bips07_1998.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/powersim.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/LF10000_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bips07_2476.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/mhd3200a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/descriptor_xingo6u.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/xingo3012.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/bips07_3078.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/orani678.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/thermal.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/LF10000_M.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/lhr04c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/cavity10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/ex26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/utm5940.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/rdist1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q4_A_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices_parallel/t2d_q9_A_24.mtx

exit 0
